 MultithreadSorting: MultithreadSorting.o
	gcc -o MultithreadSorting MultithreadSorting.o -lpthread -g
 MultithreadSorting.o: MultithreadSorting.c
	gcc -c MultithreadSorting.c -lpthread -g

 clean:
	rm MultithreadSorting.o MultithreadSorting